apiVersion: v1
kind: Service
metadata:
  name: stats-api-npservice-srv
spec:
  type: NodePort
  selector:
    app: stats-api
  ports:
    - name: stats-api
      protocol: TCP
      port: 80
      targetPort: 80