apiVersion: v1
kind: Service
metadata:
  name: test-exec-api-npservice-srv
spec:
  type: NodePort
  selector:
    app: test-exec-api
  ports:
    - name: test-exec-api
      protocol: TCP
      port: 80
      targetPort: 80