apiVersion: v1
kind: Service
metadata:
  name: theme-api-npservice-srv
spec:
  type: NodePort
  selector:
    app: theme-api
  ports:
    - name: theme-api
      protocol: TCP
      port: 80
      targetPort: 80