apiVersion: v1
kind: Service
metadata:
  name: task-api-npservice-srv
spec:
  type: NodePort
  selector:
    app: task-api
  ports:
    - name: task-api
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31005