apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
      - name: task-api
        image: markwantsapi/pts-task:latest
        env:
            - name: ASPNETCORE_ENVIRONMENT
              value: ProductionK8S
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: task-api-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: task-api
  ports:
  - name: task-api
    protocol: TCP
    port: 80
    targetPort: 80