apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gener-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gener-api
  template:
    metadata:
      labels:
        app: test-gener-api
    spec:
      containers:
      - name: test-gener-api
        image: markwantsapi/pts-test-gener:latest
        env:
            - name: ASPNETCORE_ENVIRONMENT
              value: ProductionK8S
            - name: ASPNETCORE_URLS
              value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: test-gener-api-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: test-gener-api
  ports:
  - name: test-gener-api
    protocol: TCP
    port: 80
    targetPort: 80